add_library(flight_io STATIC src/ibus.c src/rc.c src/supervisor.c src/actuators.c)
add_library(Flight::IO ALIAS flight_io)
target_include_directories(flight_io PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(flight_io PUBLIC Flight::Common)
if(NOT MSVC)
    target_link_libraries(flight_io PUBLIC m)
endif()
set_target_properties(flight_io PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
autopilot_warnings(flight_io)
